#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <array>
#include <thread>
#include <vector>

#include "game/planet/generation/EarthGenerator.hpp"
#include "support/Blocks.hpp"
#include "support/TestSeed.hpp"

using game::planet::Chunk;
using game::planet::chunkXSize;
using game::planet::chunkYSize;
using game::planet::chunkZSize;
using game::planet::EarthGenerator;

namespace {
	using ChunkBlocks = std::vector<game::BlockId>;

	constexpr std::size_t threadCount = 4;

	std::vector<glm::ivec3> area() {
		std::vector<glm::ivec3> positions;
		for (int x = -1; x <= 1; ++x)
			for (int y = -1; y <= 4; ++y)
				for (int z = -1; z <= 1; ++z)
					positions.emplace_back(x, y, z);
		return positions;
	}

	std::vector<std::size_t> ascending(const std::size_t count) {
		std::vector<std::size_t> order(count);
		for (std::size_t i = 0; i < count; ++i)
			order[i] = i;
		return order;
	}

	std::vector<std::size_t> descending(const std::size_t count) {
		std::vector<std::size_t> order = ascending(count);
		std::ranges::reverse(order);
		return order;
	}

	std::vector<std::size_t> scattered(const std::size_t count, const std::size_t stride) {
		std::vector<std::size_t> order(count);
		for (std::size_t i = 0; i < count; ++i)
			order[i] = (i * stride) % count;
		return order;
	}

	ChunkBlocks generateBlocks(const EarthGenerator& generator, const glm::ivec3& position) {
		Chunk chunk;
		generator.generateChunk(&chunk, position);

		ChunkBlocks blocks;
		blocks.reserve(game::planet::chunkVolume);
		for (int x = 0; x < chunkXSize; ++x)
			for (int y = 0; y < chunkYSize; ++y)
				for (int z = 0; z < chunkZSize; ++z)
					blocks.push_back(chunk.getBlock(x, y, z).id);
		return blocks;
	}

	std::vector<ChunkBlocks> generateArea(const EarthGenerator& generator, const std::vector<glm::ivec3>& positions,
										  const std::vector<std::size_t>& order) {
		std::vector<ChunkBlocks> result(positions.size());
		for (const std::size_t index: order)
			result[index] = generateBlocks(generator, positions[index]);
		return result;
	}
}

SCENARIO("Generating chunks in any order gives the same blocks", "[generation][order]") {
	GIVEN("an area of 54 chunks and the blocks generated for it in ascending order") {
		const std::vector<glm::ivec3> positions = area();
		const EarthGenerator          generator(test::seed);
		const auto                    reference = generateArea(generator, positions, ascending(positions.size()));

		THEN("generating it in descending order gives the same blocks") {
			REQUIRE(generateArea(generator, positions, descending(positions.size())) == reference);
		}
		AND_THEN("generating it in a scattered order gives the same blocks") {
			REQUIRE(generateArea(generator, positions, scattered(positions.size(), 7)) == reference);
			REQUIRE(generateArea(generator, positions, scattered(positions.size(), 11)) == reference);
		}
		AND_THEN("the reference is not trivial: it holds both solid and empty chunks") {
			const bool hasSolid = std::ranges::any_of(reference, [](const ChunkBlocks& blocks) {
				return std::ranges::all_of(blocks, [](const game::BlockId id) { return id != test::air; });
			});
			const bool hasEmpty = std::ranges::any_of(reference, [](const ChunkBlocks& blocks) {
				return std::ranges::all_of(blocks, [](const game::BlockId id) { return id == test::air; });
			});
			REQUIRE(hasSolid);
			REQUIRE(hasEmpty);
		}
	}
}

SCENARIO("A chunk does not depend on what was generated before it", "[generation][order]") {
	GIVEN("a chunk generated by a new generator") {
		const glm::ivec3     target(1, 2, -1);
		const EarthGenerator fresh(test::seed);
		const ChunkBlocks    alone = generateBlocks(fresh, target);

		WHEN("the whole area is generated first by another generator and the chunk after it") {
			const std::vector<glm::ivec3> positions = area();
			const EarthGenerator          busy(test::seed);
			static_cast<void>(generateArea(busy, positions, ascending(positions.size())));

			THEN("the chunk is the same") {
				REQUIRE(generateBlocks(busy, target) == alone);
			}
		}
	}
}

SCENARIO("Generating chunks on several threads gives the same blocks as one by one", "[generation][order][threads]") {
	GIVEN("the blocks of an area generated one chunk after another") {
		const std::vector<glm::ivec3> positions = area();
		const EarthGenerator          generator(test::seed);
		const auto                    reference = generateArea(generator, positions, ascending(positions.size()));

		const std::array<std::vector<std::size_t>, threadCount> orders = {
			ascending(positions.size()), descending(positions.size()), scattered(positions.size(), 7),
			scattered(positions.size(), 11)};

		WHEN("several threads generate the whole area at once, each in its own order, sharing one generator") {
			std::array<std::vector<ChunkBlocks>, threadCount> results;
			{
				std::vector<std::jthread> threads;
				threads.reserve(threadCount);
				for (std::size_t i = 0; i < threadCount; ++i)
					threads.emplace_back([&, i] { results[i] = generateArea(generator, positions, orders[i]); });
			}

			THEN("every thread produced exactly the reference blocks") {
				for (const auto& result: results)
					REQUIRE(result == reference);
			}
		}

		WHEN("several threads generate the area at once, each with a generator of its own") {
			std::array<std::vector<ChunkBlocks>, threadCount> results;
			{
				std::vector<std::jthread> threads;
				threads.reserve(threadCount);
				for (std::size_t i = 0; i < threadCount; ++i) {
					threads.emplace_back([&, i] {
						const EarthGenerator own(test::seed);
						results[i] = generateArea(own, positions, orders[i]);
					});
				}
			}

			THEN("every thread produced exactly the reference blocks") {
				for (const auto& result: results)
					REQUIRE(result == reference);
			}
		}
	}
}
